# Numpy Python Package

#### Numpy stands for numeric Python . Numpy is a library for the Python Programming language, adding support for large, multidimensional arrays and matrices, along with a large collection of high-level Mathematical functions to oprate on these array.

#### Why Numpy

 Python has many bulit types of collection , including tuples, list and sets,which have thier own purpose and benefits, however,we still miss the array we got used to un c and c++.
YOu might say I'm gotta be kidding because most of us hated arrays didn't we? but here's  the thing in the array we stored only on type of elements, for an integer array we only stored ints and same for floats and character. Why does that Matter?
Because sometimes you might wanna perrform an operation on entire array, for example let's say you have a list to store heights of people in your class and you want to find the mean of that list, you'll have to write a function to do that, and ever before that you'll need to make sure that the list contains only heights in floats.
doesn't make sense? 

In [1]:
import numpy as np

## Creating  a Numpy array

In [2]:
lst= [1,2,3]

In [3]:
np.array(lst)

array([1, 2, 3])

In [4]:
type(np.array(lst))

numpy.ndarray

In [5]:
a = np.array(lst)

In [7]:
a

array([1, 2, 3])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


##### Stacking Multiple numpy.ndarrays vertically

In [11]:
x =np.array([1,2,3])
grid = np.array([[9,8,6],[5,7,6]])
# vertically stack the arrays
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 6],
       [5, 7, 6]])

### Method avail in Numpy arrays

In [12]:
arr = np.array([123,3,4,55,98,64])

In [13]:
arr.max()

123

In [14]:
arr.sum()

347

In [15]:
arr.mean()

57.833333333333336

In [17]:
arr.argmax()
#Return indices of the maximum values along the given axis

0

In [18]:
print(arr)

[123   3   4  55  98  64]


In [21]:
print(arr.shape)

(6,)


###### Rehaping the array, shape-rows and colums

In [22]:
arr = arr.reshape(2,3)
print(arr)

[[123   3   4]
 [ 55  98  64]]


In [23]:
arr.shape

(2, 3)

#### The Numpy arange() Function

In [24]:
# It's similar to range function in function

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [28]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat[0,1]

1

In [31]:
mat[5,6] # mat[row , column]

56

In [32]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [34]:
mat[0:3,0:3] # mat[0row:3row , 0column:3column]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [35]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Numpy array is mutable

In [36]:
a  = np.array([1,2,3])

In [37]:
a[0]= 5

In [38]:
a


array([5, 2, 3])

In [41]:
a.flags.writeable = False # after this line of code we are not able to edit the array or cannot assigns the other values

In [43]:
a[2] = 6 

ValueError: assignment destination is read-only

In [44]:
a.flags.writeable  =True

a[2]= 6

In [45]:
a

array([5, 2, 6])

In [46]:
Data = [[1.74, 1.45, 1.58, 1.80],
        [58.2, 60.0, 61.2, 63.2]]


In [48]:
heights = Data[0]
weights = Data[1]

In [49]:
print(heights)

[1.74, 1.45, 1.58, 1.8]


In [50]:
print(weights)

[58.2, 60.0, 61.2, 63.2]


###### Suppose you want BMI or Body Mass Index of every person
    BMI = weight/height **2

In [51]:
BMI =[]
for weight,height in zip(weights,heights):
    BMI.append(weight / height **2)
    
print(BMI)

[19.223147047166073, 28.53745541022592, 24.515302034930297, 19.506172839506174]


In [52]:
np_height =np.round(np.random.normal(1.75,0.20,5000),2)
np_weight =np.round(np.random.normal(60.32,15,5000),2)


In [53]:
print(np_height)
print(np_weight)

[1.56 1.71 1.73 ... 1.81 2.   1.82]
[85.29 30.76 77.87 ... 53.93 70.33 71.12]


In [54]:
np_height.shape

(5000,)

In [55]:
BMI = np_weight/np_height **2

In [56]:
print(BMI)

[35.04684418 10.51947608 26.01824318 ... 16.46164647 17.5825
 21.47083686]


In [57]:
np_data  =np.column_stack((np_height,np_weight))

## More with Numpy
Calculating mean median

In [58]:
np.mean(np_height)

1.7472559999999997

In [59]:
np.median(np_weight)

60.31

In [60]:
np.median(np_height)

1.75

### corelation coefficient

--More in stats --
Coreation coefficient is a number between -1 and 1 that signifies how closely two variables x and y(e.g. heights and weights)  That belong to same record, depend on each other

In [61]:
np.corrcoef(np_height,np_weight)

array([[ 1.        , -0.00465319],
       [-0.00465319,  1.        ]])